#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9
ENV_FILE="${WEGWAERTS_ENV_FILE:-.env.production.local}"

banner "Wegwärts production setup"

stage "Legal launch gate"
warn "The public demo intentionally contains no postal address. This leaves a legal risk."
step "Verify that /impressum and /datenschutz show Bobby Ly and bobbyly04@gmail.com."
step "Review provider regions, contracts, data transfers, and log-retention details before launch."
if ! confirm "Do you consciously want to continue without publishing a postal address?"; then
  warn "Stopping before external resources are created."
  exit 1
fi

stage "Neon production database"
open_url "https://console.neon.tech/app/projects"
step "Create a Free project in an appropriate EU region."
step "Open Connect and copy the pooled connection string (hostname contains -pooler)."
ask_secret DATABASE_URL "Paste the pooled runtime DATABASE_URL:"
step "Switch pooling off and copy the direct connection string."
ask_secret DATABASE_MIGRATION_URL "Paste the direct DATABASE_MIGRATION_URL:"
write_env DATABASE_URL "$DATABASE_URL"
write_env DATABASE_MIGRATION_URL "$DATABASE_MIGRATION_URL"

stage "Cloudflare Workers AI"
open_url "https://dash.cloudflare.com/profile/api-tokens"
step "Create a least-privilege token that can invoke Workers AI for your account."
ask CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
ask_secret CLOUDFLARE_AI_API_TOKEN "Paste the Workers AI API token:"
write_env CLOUDFLARE_ACCOUNT_ID "$CLOUDFLARE_ACCOUNT_ID"
write_env CLOUDFLARE_AI_API_TOKEN "$CLOUDFLARE_AI_API_TOKEN"
write_env CLOUDFLARE_AI_MODEL "@cf/qwen/qwen3-30b-a3b-fp8"

stage "Cloudflare Turnstile"
open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
step "Create a Managed widget and allow the hostname wegwaerts.bobbyly.com."
ask NEXT_PUBLIC_TURNSTILE_SITE_KEY "Paste the public Turnstile site key:"
ask_secret TURNSTILE_SECRET_KEY "Paste the Turnstile secret key:"
write_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$NEXT_PUBLIC_TURNSTILE_SITE_KEY"
write_env TURNSTILE_SECRET_KEY "$TURNSTILE_SECRET_KEY"

stage "Generate application secrets"
SESSION_SECRET=$(openssl rand -hex 32)
IP_HASH_SECRET=$(openssl rand -hex 32)
CRON_SECRET=$(openssl rand -hex 32)
write_env SESSION_SECRET "$SESSION_SECRET"
write_env IP_HASH_SECRET "$IP_HASH_SECRET"
write_env CRON_SECRET "$CRON_SECRET"
write_env APP_ORIGIN "https://wegwaerts.bobbyly.com"
write_env PUBLIC_DEMO "true"
write_env AI_PROVIDER "workers-ai"
write_env AI_ENABLED "true"
write_env AI_MAX_OUTPUT_TOKENS "500"

stage "Apply production migrations"
warn "This changes the Neon production schema."
if confirm "Run the committed Drizzle migrations against Neon now?"; then
  DATABASE_MIGRATION_URL="$DATABASE_MIGRATION_URL" pnpm db:migrate
else
  SKIPPED+=("Production database migration")
fi

stage "Create the Vercel project"
open_url "https://vercel.com/new"
step "Import github.com/bobby1y04/wegw-rts with the Next.js preset."
step "Open Project Settings → Environment Variables and add every key from $ENV_FILE to Production only."
step "Do not expose production values to Preview or Development."
pause "Continue after Vercel has completed a production deployment."

stage "Add the production subdomain"
open_url "https://vercel.com/dashboard"
step "Open the Wegwärts project → Settings → Domains."
step "Add wegwaerts.bobbyly.com and copy the exact CNAME target Vercel shows."
ask VERCEL_CNAME_TARGET "Paste the Vercel CNAME target:"
open_url "https://dash.cloudflare.com/"
step "Open bobbyly.com → DNS → Records."
step "Create CNAME name=wegwaerts target=$VERCEL_CNAME_TARGET with DNS only (gray cloud), TTL Auto."
pause "Continue after Vercel reports the domain as verified and TLS is active."

stage "Production launch checks"
open_url "https://wegwaerts.bobbyly.com"
step "Complete onboarding in one browser and verify a private/incognito browser starts separately."
step "Verify Turnstile, one streamed mentor answer, data deletion, and the daily cleanup cron."
step "Check response headers for CSP, HSTS, no-store, nosniff, and no X-Powered-By."
step "Confirm Workers AI paid overages are disabled and all free-tier alerts are enabled."
if ! confirm "Did every launch check pass?"; then
  warn "Keep the LinkedIn link unpublished until all checks pass."
  exit 1
fi

finish
